### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Romk-a** [cyborg-one/nfqttl#1]
Привет дружище! Подскажи, есть ли у тебя телеграм-канал или чатик, чтобы можно было следить за обновлениями твоего модуля? Он очень хорош. Я для  xiaomi ми9 сделал модуль ядра для поддержки ттл, и твой модуль по красоте прям заходит.

**Comment by cyborg-one** [comment]
Привет, телеграм канала нет, в чатиках тоже не сижу, со следующей версией добавлю в официальный репозиторий магиска и обновление будет через магиск.
