### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Paxani4ek** [cyborg-one/nfqttl#10]
Please, help.  Xiaomi 11 ultra , a12 Xiaomi eu 22.6.9 .  Does not fix TTL or the Internet does not work at all.

**Comment by cyborg-one** [comment]
Run the commands on the command line and send the output of each one. Run commands with the nfqttl module installed, mobile data enabled, and hotspot enabled.
su
ip -4 route list scope global
ip -4 addr list
iptables -t mangle -vnL

Restart nfqttl with commands, open some site then send the output from the command line.
pkill -9 nfqttl
/data/adb/magisk/nfqttl/nfqttl -u

**Comment by cyborg-one** [comment]
> /data/adb/magisk/nfqttl/nfqttl -u
I have edited my post.
/data/adb/modules/nfqttl/nfqttl -u

>2.1.2 It seems to work, I will still test it.
Any way, it looks like you found a solution to your problem.

**Comment by Paxani4ek** [comment]
for beer
