### ISSUE TITLE
Version 2.8 cannot hide modem mode.

### ISSUE THREAD

**Issue by LordArrin** [cyborg-one/nfqttl#11]
I use this module in Lenovo J607F (wi-fi) and Poco F3, both on Android 12L (api 32). Version 2.7 works perfect, but with 2.8 my operator broke the connection after 2-3 minutes. Can give any logs that may help.

**Comment by cyborg-one** [comment]
Run the commands on the command line and send the output of each one. Run commands with the nfqttl version 2.8 module installed, mobile data enabled, and hotspot enabled on hotspot device.

su
ip -4 route list scope global table all
ip -4 addr list
iptables -t mangle -vnL

Restart nfqttl with commands.

pkill -9 nfqttl
/data/adb/modules/nfqttl/nfqttl -u

Open github.com site in browser go back to console then send the output from the command line.
Ctrl+c
/data/adb/modules/nfqttl/nfqttl -u -d -s

**Comment by LordArrin** [comment]
With 2.8? If yes, then only on Sunday, I'm very busy now.

**Comment by cyborg-one** [comment]
>With 2.8?

Yes.
>on Sunday,

Ok.

**Comment by LordArrin** [comment]
~ $ su
p -4 route list scope global table all                <
default via 10.47.140.149 dev rmnet_data2 table rmnet_data2 proto static mtu 1500
:/data/data/com.termux/files/home # ip -4 addr list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
13: rmnet_data2@rmnet_mhi0: <UP,LOWER_UP> mtu 1500 qdisc mq state UNKNOWN group default qlen 1000
    inet 10.47.140.148/29 scope global rmnet_data2
       valid_lft forever preferred_lft forever
24: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    inet 192.168.186.225/24 brd 192.168.186.255 scope global wlan1
       valid_lft forever preferred_lft forever
ptables -t mangle -vnL                                <
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 8200 2090K nfqttli    all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain INPUT (policy ACCEPT 5949 packets, 1211K bytes)
 pkts bytes target     prot opt in     out     source               destination
 8409 2529K wakeupctrl_mangle_INPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 8409 2529K routectrl_mangle_INPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 959 packets, 154K bytes)
 pkts bytes target     prot opt in     out     source               destination
  959  154K tetherctrl_mangle_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
12523 3544K nfqttlo    all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain POSTROUTING (policy ACCEPT 10439 packets, 2042K bytes)
 pkts bytes target     prot opt in     out     source               destination
13397 3130K qcom_htimer_POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13397 3130K oem_mangle_post  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13397 3130K bw_mangle_POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13397 3130K idletimer_mangle_POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13397 3130K qcom_qos_reset_POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0
13397 3130K qcom_qos_filter_POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain bw_mangle_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  *      ipsec+  0.0.0.0/0            0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            policy match dir out pol ipsec
13397 3130K MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK and 0xffefffff
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 1029
13397 3130K            all  --  *      *       0.0.0.0/0            0.0.0.0/0           match bpf pinned /sys/fs/bpf/prog_netd_skfilter_egress_xtbpf

Chain idletimer_mangle_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
 7429 1784K IDLETIMER  all  --  *      rmnet_data2  0.0.0.0/0            0.0.0.0/0            timeout:10 label:0 send_nl_msg

Chain nfqttli (1 references)
 pkts bytes target     prot opt in     out     source               destination
 8200 2090K NFQUEUE    all  --  *      *       0.0.0.0/0            0.0.0.0/0            NFQUEUE num 6464

Chain nfqttlo (1 references)
 pkts bytes target     prot opt in     out     source               destination
12523 3544K NFQUEUE    all  --  *      *       0.0.0.0/0            0.0.0.0/0            NFQUEUE num 6464

Chain nm_mdmprxy_icmp_pkt_marker (0 references)
 pkts bytes target     prot opt in     out     source               destination

Chain nm_mdmprxy_mark_prov_chain (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 nm_mdmprxy_pkt_skmark  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            socket --transparent --nowildcard --restore-skmark
    0     0 nm_mdmprxy_pkt_skmark  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            socket --transparent --nowildcard --restore-skmark

Chain nm_mdmprxy_mngl_post (0 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xf0002 MARK and 0x0

Chain nm_mdmprxy_mngl_pre (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain nm_mdmprxy_mngl_pre_ex (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain nm_mdmprxy_mngl_pre_spi (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain nm_mdmprxy_mngl_pre_tee (0 references)
 pkts bytes target     prot opt in     out     source               destination

Chain nm_mdmprxy_pkt_forwarder (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain nm_mdmprxy_pkt_marker (0 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 CONNMARK   all  --  *      *       0.0.0.0/0            0.0.0.0/0            CONNMARK restore
    0     0 nm_mdmprxy_mngl_pre  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 nm_mdmprxy_mark_prov_chain  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 nm_mdmprxy_mngl_pre_spi  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 nm_mdmprxy_mngl_pre_ex  all  --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 MARK       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:7275 MARK set 0xf0002
    0     0 MARK       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:5060 MARK set 0xf0002
    0     0 MARK       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:5060 MARK set 0xf0002
    0     0 nm_mdmprxy_pkt_forwarder  all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xf0002
    0     0 DROP      !icmp --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xf0002

Chain nm_mdmprxy_pkt_skmark (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain oem_mangle_post (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain qcom_htimer_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain qcom_qos_filter_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination

Chain qcom_qos_reset_POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
 7431 1784K MARK       all  --  *      rmnet_data+  0.0.0.0/0            0.0.0.0/0            MARK and 0x0

Chain routectrl_mangle_INPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  rmnet_data1 *       0.0.0.0/0            0.0.0.0/0            MARK xset 0xf0001/0xffefffff
 3240 1296K MARK       all  --  rmnet_data2 *       0.0.0.0/0            0.0.0.0/0            MARK xset 0x30064/0xffefffff
    4   510 MARK       all  --  wlan1  *       0.0.0.0/0            0.0.0.0/0            MARK xset 0x30063/0xffefffff

Chain tetherctrl_mangle_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination
   82  4896 TCPMSS     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp flags:0x02/0x02 TCPMSS clamp to PMTU

Chain wakeupctrl_mangle_INPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination
:/data/data/com.termux/files/home # pkill -9 nfqttl
data/adb/modules/nfqttl/nfqttl -u                     <
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
unbinding existing nf_queue handler for AF_INET6 (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding nfnetlink_queue as nf_queue handler for AF_INET6
binding this socket to queue '6464'
change ttl to '64'
Split tcp package '0'
setting copy_packet mode
set uid 6464
Waiting for packets...
name index ttl iout iin rmnet_data2 13 64 0 13
/data/adb/modules/nfqttl/nfqttl -u -d -s
^C
data/adb/modules/nfqttl/nfqttl -u -d -s               <
opening library handle
unbinding existing nf_queue handler for AF_INET (if any)
unbinding existing nf_queue handler for AF_INET6 (if any)
binding nfnetlink_queue as nf_queue handler for AF_INET
binding nfnetlink_queue as nf_queue handler for AF_INET6
binding this socket to queue '6464'
change ttl to '64'
Split tcp package '1'
setting copy_packet mode
set uid 6464
daemonize
:/data/data/com.termux/files/home #


Here it is.

**Comment by cyborg-one** [comment]
No errors.
Show the value of ttl.
Go to the command line on the device with the hotspot, run tcpdump. On the receiving device, ping 8.8.8.8. Then send the output of tcpdump.

tcpdump -vvvnnc 10 -i  rmnet_data2 dst 8.8.8.8

**Comment by LordArrin** [comment]
~ $ su
cpdump -vvvnnc 10 -i rmnet_data2 dst 8.8.8.8          <
tcpdump: listening on rmnet_data2, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
18:00:40.674571 IP (tos 0x0, ttl 64, id 26920, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 79, length 64
18:00:41.676062 IP (tos 0x0, ttl 64, id 26927, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 80, length 64
18:00:42.677717 IP (tos 0x0, ttl 64, id 27029, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 81, length 64
18:00:43.690498 IP (tos 0x0, ttl 64, id 27116, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 82, length 64
18:00:44.685425 IP (tos 0x0, ttl 64, id 27207, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 83, length 64
18:00:45.682515 IP (tos 0x0, ttl 64, id 27269, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 84, length 64
18:00:46.684819 IP (tos 0x0, ttl 64, id 27427, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 85, length 64
18:00:47.684699 IP (tos 0x0, ttl 64, id 27615, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 86, length 64
18:00:48.687957 IP (tos 0x0, ttl 64, id 27746, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 87, length 64
18:00:49.691437 IP (tos 0x0, ttl 64, id 27947, offset 0, flags [DF], proto ICMP (1), length 84)
    10.3.32.215 > 8.8.8.8: ICMP echo request, id 1, seq 88, length 64
10 packets captured
10 packets received by filter
0 packets dropped by kernel
:/data/data/com.termux/files/home #

**Comment by LordArrin** [comment]
And tablet says "Device connection is limited"

**Comment by cyborg-one** [comment]
Let's look at packets with a ttl value other than 64 by excluding those packets from tcpdump.

We go to the command line on the device with an access point, run tcpdump. On the receiving device, open some a website in a browser. Then send the output of tcpdump.

tcpdump -vvvnnc 10 src 10.3.32.215 and 'ip[8] != 64'

Notice: the address 10.3.32.215, this is the current address of rmnet_data2, which can be seen by calling the command.

ip -4 route list scope global table all

**Comment by LordArrin** [comment]
nothing happened)

**Comment by LordArrin** [comment]
Tablet had 2.7 version installed, does it matter?

**Comment by LordArrin** [comment]
~ $ su
p -4 route list scope global table all                <
default via 10.206.205.22 dev rmnet_data2 table rmnet_data2 proto static mtu 1500
cpdump -vvvnnc 10 src 10.206.205.22 and 'ip[8] != 64' <
tcpdump: listening on wlan1, link-type EN10MB (Ethernet), capture size 262144 bytes

**Comment by cyborg-one** [comment]
>nothing happened)

This means that 262144 bytes of packets have a ttl value of 64.

Try the following commands and check your internet connection.

pkill -9 nfqttl
/data/adb/modules/nfqttl/nfqttl -d -u
iptables -t mangle -I POSTROUTING -j MARK --set-mark 0
iptables -t mangle -I PREROUTING -j MARK --set-mark 0

**Comment by LordArrin** [comment]
Lol, on tablet i have internet, but on phone it does not work)
I didn't enter commands at this time)

Alright, let's go.

**Comment by cyborg-one** [comment]
Looks like tcpdup misread the default interface.

> tcpdump: listening on wlan1

Please do it again

Let's look at packets with a ttl value other than 64 by excluding those packets from tcpdump.

We go to the command line on the device with an access point, run tcpdump. On the receiving device, open some a website in a browser. Then send the output of tcpdump.

tcpdump -vvvnnc 10 -i rmnet_data2 src 10.3.32.215 and 'ip[8] != 64'

Notice: the address 10.3.32.215, this is the current address of rmnet_data2, which can be seen by calling the command.

ip -4 route list scope global table all

**Comment by LordArrin** [comment]
Wait, man, I use your commands (iptables .... ) and internet become work)

**Comment by cyborg-one** [comment]
Maybe you have mobile data restriction turned limit on in your settings?

**Comment by LordArrin** [comment]
~ $ su
p -4 route list scope global table all                <
default via 10.12.118.49 dev rmnet_data2 table rmnet_data2 proto static mtu 1500
 -i rmnet_data2 src 10.12.118.49 and 'ip[8] != 64'    <
tcpdump: listening on rmnet_data2, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes

**Comment by LordArrin** [comment]
> Maybe you have mobile data restriction turned limit on in your settings?

No, i have ulimited internet, but with restricted sharing. And on phone all restrictions are turned off.

**Comment by cyborg-one** [comment]
>Wait, man, I use your commands (iptables .... ) and internet become work)

Is the internet working now?

**Comment by LordArrin** [comment]
> Is the internet working now?

Yep, but doesn't checked my operator. 
This maneuver can cost me $1  -_o

**Comment by cyborg-one** [comment]
Since tcpdup did not return a ttl value other than 64, this means that the module is working. You can reboot the devices, check the internet and your carrier, and in case the internet doesn't work, execute the commands and say that they solve the problem.

**Comment by LordArrin** [comment]
> Since tcpdup did not return a ttl value other than 64, this means that the module is working. You can reboot the devices, check the internet and your carrier, and in case the internet doesn't work, execute the commands and say that they solve the problem?

Alright, I'll write the answer, just wait for some "happy" news from operator. Hope that they're not see this)

**Comment by LordArrin** [comment]
Yeah, after entering this commands all works fantastic! I'll test it today, and write later.

> ![Screenshot_20220620-061336_Termux.png](https://user-images.githubusercontent.com/79581469/174519026-29031d44-cf07-47d5-bf3d-e01bef778342.png)

**Comment by LordArrin** [comment]
Good, almost one hour, and still amazing flight! MTS, take it, bastards)

**Comment by cyborg-one** [comment]
Restart nfqttl with commands.

pkill -9 nfqttl
/data/adb/modules/nfqttl/nfqttl -d  -s -u --countpacket=100

And check the internet connection, if there is no connection, refresh the page 2-5 times. And write about the result.

**Comment by LordArrin** [comment]
![Screenshot_20220620-201606_Chrome.png](https://user-images.githubusercontent.com/79581469/174651894-4894d83f-3bd4-430a-b747-33dd0f25a8bc.png)

**Comment by LordArrin** [comment]
I have the disconnections before, even on 2.7, just not so quick and annoying. But I will try 2.1.2 tomorrow. I can give you remote access, if it can help.

**Comment by Ilya87** [comment]
The same issue Redmi Note 7, MTS. Use of nfq ttl 2.8 even without tethering blocks access to the most internet sites.

**Comment by LordArrin** [comment]
Forgot it sorry, I delete the module from tablet and write iptables commands from up message. Works good, after 4 or 5 hours I got one disconnect, but i can live with that. I'll try 2.1.2 tomorrow.

**Comment by LordArrin** [comment]
Still got a disconnections sometimes. 2.1.2

**Comment by cyborg-one** [comment]
Maybe it will help to install only ipv4 in the apn settings. I don't know what is causing this problem. If the module is not working for you, you need to find another way.

**Comment by LordArrin** [comment]
> Maybe it will help to install only ipv4 in the apn settings. I don't know what is causing this problem. If the module is not working for you, you need to find another way.

Already set. Looks like my operator just a m...cker, so I gonna change him. Anyway, thanks for the help) 👍🏻

**Comment by Ilya87** [comment]
Version 2.7 works flowlessly.
