### ISSUE TITLE
rejected by latest magisk 

### ISSUE THREAD

**Issue by junbr0** [cyborg-one/nfqttl#20]
module wont installed on latest magisk 28.1

**Comment by cyborg-one** [comment]
Gives an error? On my device, when installing modules, the Magisk app version 28.1 crashes, but when installing via TWRP, the module is installed and works. There is a problem with installing modules in the Magisk repository. It seems to be a problem with the Magisk app.

**Comment by junbr0** [comment]
reflash from nougat to oreo.. no complain.
